FROM ubuntu:18.04

RUN curl -fOL https://github.com/cdr/code-server/releases/download/v3.6.1/code-server_3.6.1_amd64.deb \
    && sudo dpkg -i code-server_3.6.1_amd64.deb \
    && rm code-server_3.6.1_amd64.deb

WORKDIR /home/coder

EXPOSE 8080
ENTRYPOINT ["dumb-init", "/usr/bin/code-server", "--bind-addr", "0.0.0.0:8080", "--auth", "none", "."]
